### PR TITLE
Adds Skip Navigation link

### PR DESCRIPTION
**Pull request by michaelck**
## Summary

Provides skip navigation link for those visitors relying on screen readers or keyboard based browsing.

Bootstrap provides an example using .sr-only classes for this purpose: 
http://v4-alpha.getbootstrap.com/components/utilities/#screen-readers
## What's included in this PR

Two files have been appeneded:
- **index.php** - adds the #content to .main-container div
- **navigation-default.php** - anchor element added above nav element which links to #content

P.S. Great project!

### CODE REVIEW

**Comment by digitaldesigndj** [comment]
Thank you this looks like a good addition, I'm very glad you like the project!

**Comment by michaelck** [comment]
Thanks for the merge :+1:

**Comment by digitaldesigndj** [comment]
:+1:  I'm very interested in seeing how you use the theme, here's a link to one of my projects: http://stage.alanteair.com/

**Comment by digitaldesigndj** [comment]
Happy to help, a little hesitant to help naked mole rats with design, but very happy nonetheless.

Context for the future: avatar Chicken, was talking to avatar pink kitten, and was called naked mole rat by avatar pixelated and stolen from Star Bound chicken avatar. Kitten appeared nekkid.

**Comment by digitaldesigndj** [comment]
Jade bunnie was added to file-icons nonetheless

**Comment by digitaldesigndj** [comment]
(Secretly wonders if jade bunnie should have been, jade colored? Instead of red.

**Comment by digitaldesigndj** [comment]
)

**Comment by digitaldesigndj** [comment]
Wrong thread! https://github.com/DanBrooker/file-icons/commit/424bb4468b2fa7984ab49a6f546c69642c931b67

**Pull request merged**
